### ISSUE TITLE
Docker image with all dependency versions?

### ISSUE THREAD

**Issue by codecat741** [kdmayer/3D-PV-Locator#5]
Great work on this. But the dependencies are all outdated and it's not possible to install them anymore. By chance do you have a docker image for it?

**Comment by kdmayer** [comment]
Hi,

I am looking into this at the moment. Will probably make a push with the docker file tomorrow or the day after.

Thanks,

Kevin

**Comment by codecat741** [comment]
Thanks so much, Kevin!

**Comment by kdmayer** [comment]
Ok, I uploaded the Dockerfile and updated the usage instructions in the README.

Let me know if you run into issues.

Thanks,

Kevin

**Comment by codecat741** [comment]
You, sir, are a national treasure.

From: Kevin ***@***.***>
Date: Thursday, July 6, 2023 at 7:46 PM
To: kdmayer/3D-PV-Locator ***@***.***>
Cc: Cory Decker ***@***.***>, Author ***@***.***>
Subject: Re: [kdmayer/3D-PV-Locator] Docker image with all dependency versions? (Issue #5)

Ok, I uploaded the Dockerfile and updated the usage instructions in the README.

Let me know if you run into issues.

Thanks,

Kevin
