### ISSUE TITLE
Accessing the bucket

### ISSUE THREAD

**Issue by Federklein** [kdmayer/3D-PV-Locator#6]
I can't access the bucket when trying to download the model from AWS.
This is the error message when i simply paste in the command from the instructions.
aws s3 cp --request-payer requester s3://pv4ger/NRW_models/inceptionv3_weights.tar models/classification/

fatal error: An error occurred (400) when calling the HeadObject operation: Bad Request

Did something change in the syntax for AWS or is the bucket not available anymore?
i got my Access tokens correct and the region set as eu-central-1.

Greetings,
Simon

**Comment by kdmayer** [comment]
Hi Simon,

The bucket is still available and I am able to execute the above mentioned command without an error on my local machine, i.e., I can download the model checkpoint. Maybe your aws cli is not set up correctly?

Best,
Kevin
